version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mydb
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
